# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-09-20 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cardid', models.CharField(max_length=64)),
                ('timeframe', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('authority', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name', 'cardid')]),
        ),
    ]
