# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-11-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date1', models.DateTimeField(auto_now=True, null=True)),
                ('date2', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
