# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-10-11 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='headphoto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
