# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-11-23 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20191011_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('issue', models.CharField(max_length=512)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='headphoto',
            new_name='photo',
        ),
    ]
